############################################
# +---------------------------------------+#
# |         Config Revision 17            |#
# +---------------------------------------+#
############################################

# -------------------------------------------------------------------------------------------------------------------
FoodChest:
    type: SUPPLYCRATE # Place a chest down, and the chest will be filled with items
    item: 'CHEST 1 name:&c[&6Foodie_&eChest&c]_&f#124 lore:&7Mmmm,_something_smells_good.|&8Place_the_chest_down_to_obtain_a_pack_of_food! glow:true'
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a &c[&6Foodie &eChest&c] &f#124'
        broadcast: ''
    effect:
        1:
          class: AtomEffect
    reward:
        minimum-rewards: 8
        maximum-rewards: 15
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon_block 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(log 1)'
            - 'unique:(),     chance:(1),          item:(web 1)'
            - 'unique:(),     chance:(1),          item:(pork 1)'
            - 'unique:(),     chance:(1),          item:(raw_beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_soup 1)'
# -------------------------------------------------------------------------------------------------------------------
FoodPack:
    type: MYSTERYCRATE # Right, or left click to receive rewards
    item: 'minecart 1 name:&c[&6Foodie_&ePack&c]_&f#125 lore:&7Mmmm,_something_smells_good.|&8Right_click_to_receive_a_pack_of_food! glow:true'
    confirmation:
        enabled: true
        accept-button: 'STAINED_GLASS_PANE:5 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'STAINED_GLASS_PANE:14 1 name:&4No'
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a &c[&6Foodie &ePack&c] &f#125'
        broadcast: ''
    effect:
        1:
          class: HeartEffect
    reward:
        minimum-rewards: 3
        maximum-rewards: 3
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon_block 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(log 1)'
            - 'unique:(),     chance:(1),          item:(web 1)'
            - 'unique:(),     chance:(1),          item:(pork 1)'
            - 'unique:(),     chance:(1),          item:(raw_beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_soup 1)'
# -------------------------------------------------------------------------------------------------------------------
FoodKey:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'NETHER_STAR 1 name:&c[&6Foodie_Key&c]_&f#1 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
    animation: 'none'
    display-name: '&c[&6Foodie Key&c] &f#1'
    holographic:
        - '{crate-name}'
        - '{lore:1}'
    confirmation:
        enabled: true
        accept-button: 'STAINED_GLASS_PANE:5 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'STAINED_GLASS_PANE:14 1 name:&4No'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a {crate}'
        broadcast: ''
    effect:
        1:
          class: Star
          category: PERSISTENT
          particles: 5
    reward:
        minimum-rewards: 3
        maximum-rewards: 3
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon_block 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(log 1)'
            - 'unique:(),     chance:(1),          item:(web 1)'
            - 'unique:(),     chance:(1),          item:(pork 1)'
            - 'unique:(),     chance:(1),          item:(raw_beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_soup 1)'
# -------------------------------------------------------------------------------------------------------------------
# An example of a key crate with animations (Roulette)
FoodKeyT2:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'NETHER_STAR 1 name:&c[&6Foodie_&eKey&c]_&f#2 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
    animation: 'ROULETTE'
    display-name: '&c[&6Foodie Crate&c] &f#2'
    holographic:
        - '{crate-name}'
        - '{lore:1}'
    confirmation:
        enabled: true
        accept-button: 'STAINED_GLASS_PANE:5 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'STAINED_GLASS_PANE:14 1 name:&4No'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a {crate}'
        broadcast: ''
    effect:
        1:
          class: HeartEffect
    reward:
        minimum-rewards: 1
        maximum-rewards: 1
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon_block 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(log 1)'
            - 'unique:(),     chance:(1),          item:(web 1)'
            - 'unique:(),     chance:(1),          item:(pork 1)'
            - 'unique:(),     chance:(1),          item:(raw_beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_soup 1)'
# -------------------------------------------------------------------------------------------------------------------
# An example of a key crate with animations (CSGO)
FoodKeyT3:
    type: KEYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'NETHER_STAR 1 name:&c[&6Foodie_&eKey&c]_&f#3 lore:&7Mmmm,_something_smells_good.|&8Right_click_a_chest_to_receive_a_pack_of_food! glow:true'
    animation: 'CSGO'
    display-name: '&c[&6Foodie Key&c] &f#3'
    holographic:
        - '{crate-name}'
        - '{lore:1}'
    confirmation:
        enabled: true
        accept-button: 'STAINED_GLASS_PANE:5 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'STAINED_GLASS_PANE:14 1 name:&4No'
    preview:
        enabled: true
        rows: 2
    buy:
        enabled: false
        cost: 0
    message:
        open: '{p}You have opened a {crate}'
        broadcast: ''
    effect:
        1:
          class: HeartEffect
          category: PERSISTENT
    reward:
        minimum-rewards: 1
        maximum-rewards: 1
        rewards:
            - 'unique:(),     always:(),           cmd:(heal {player}), display:(gold_block 1 name:&fHeal! lore:&r&eOpen_for_an_instant_heal! glow:true)'
            - 'unique:(),     chance:(1),          item:(cake 1 name:&fThe_cake_is_a_lie!)'
            - 'unique:(),     chance:(1),          item:(apple 1)'
            - 'unique:(),     chance:(1),          item:(golden_apple 1)'
            - 'unique:(),     chance:(1),          item:(bone 1)'
            - 'unique:(),     chance:(1),          item:(bread 1)'
            - 'unique:(),     chance:(1),          item:(melon 1)'
            - 'unique:(),     chance:(1),          item:(ice 1)'
            - 'unique:(),     chance:(1),          item:(snow 1)'
            - 'unique:(),     chance:(1),          item:(melon_block 1)'
            - 'unique:(),     chance:(1),          item:(dirt 1)'
            - 'unique:(),     chance:(1),          item:(sand 1)'
            - 'unique:(),     chance:(1),          item:(log 1)'
            - 'unique:(),     chance:(1),          item:(web 1)'
            - 'unique:(),     chance:(1),          item:(pork 1)'
            - 'unique:(),     chance:(1),          item:(raw_beef 1)'
            - 'unique:(),     chance:(1),          item:(cooked_beef 1)'
            - 'unique:(),     chance:(1),          item:(mushroom_soup 1)'

