#
# Spawn Egg Crate
# Created by imWillX
#

SpawnEgg:
    type: KeyCrate
    displayName: '&fSpawn Eggs'
    preview:
        enabled: true
    buy:
        enabled: false
        cost: 0
    message:
        onOpen: ''
        broadcast: ''
    key:
        item: '383:4'
        enchantment: '300:1'
        name: '&fEgg Key'
        lore:
            - '&6Testing...'
    effect:
        onOpenEffects: ''
        dormantEffects: 'witchMagic'
    reward:
        minimumRewards: 1
        maximumRewards: 1
        rewards:
            - 'chance:(1), item:(383:4)' # Elder
            - 'chance:(1), item:(383:6)' # Stray
            - 'chance:(1), item:(383:23)' # Husk
            - 'chance:(1), item:(383:27)' # Zombie Villager
            - 'chance:(1), item:(383:34)' # Evoker
            - 'chance:(1), item:(383:35)' # Vex
            - 'chance:(1), item:(383:36)' # Vindicator
            - 'chance:(1), item:(383:37)' # Illusioner
            - 'chance:(1), item:(383:50)' # Creeper
            - 'chance:(1), item:(383:56)' # Ghast
            - 'chance:(1), item:(383:67)' # Endermite
            - 'chance:(1), item:(383:68)' # Guardian
            - 'chance:(1), item:(383:69)' # Shulker
            - 'chance:(1), item:(383:100)' # Horse 
            - 'chance:(1), item:(383:101)' # Rabbit
            - 'chance:(1), item:(383:102)' # Polar Bear
            - 'chance:(1), item:(383:103)' # Llama
            - 'chance:(1), item:(383:105)' # Parrot
            - 'chance:(1), item:(383:120)' # Villager   

